name: Fetch Extended Data

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Fetch Volume & Fees
        run: python fetch_volume_fees.py

      - name: Commit & push updated CSV if changes exist
  env:
    GH_PAT: ${{ secrets.GH_PAT }}
  run: |
    git config user.name "github-actions"
    git config user.email "actions@github.com"
    git add data/volume_fees.csv
    git diff --cached --quiet || git commit -m "Update volume_fees.csv"
    git push https://x-access-token:${GH_PAT}@github.com/vadymdi/extended-dash.git HEAD:main
