name: Fetch Extended Data (volume_fees)

on:
  schedule:
    - cron: "0 6 * * *"    # раз на день 06:00 UTC 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch (append mode)
        run: python fetch_volume_fees.py

      - name: Show data dir
        run: ls -la data || true

      - name: Commit & push only if changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/volume_fees.csv
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Update volume_fees.csv [ci skip]" || true
            git push origin HEAD:main
          fi
